name: Vendo arquivos compartilhados entre Steps

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch #sÃ³ roda com o play

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de GitHub ACtions da LinuxTips" > mensagem.txt

      - name: Onde estou
        run: ls -lha

      - name: Exibir arquivo
        run: cat mensagem.txt

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Onde estou
        run: ls -lha

      - name: Exibir arquivo
        run: cat mensagem.txt