name: Vendo arquivos compartilhados entre Steps

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de GitHub ACtions da LinuxTips" > ${{ github.workspace }}/mensagem.txt

      - uses: actions/upload-artifact@v4
        with:
          name: strigus-upload
          path: ${{ github.workspace }}/mensagem.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Onde estou
        run: ls -lha

      - uses: actions/download-artifact@v4
        with:
          name: strigus-upload
          path: strigus

      - name: Ver o conteudo do diretorio
        run: ls -lha && ls ./strigus/    

      - name: Acessa arquivo
        run: mv strigus/mensagem.txt . && rm -rf ./strigus

      - name: Ver o conteudo do diretorio
        run: ls -lha

      - name: Acessa arquivo
        run: cat mensagem.txt